# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-17 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='father',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Soltero'), ('married', 'Casado'), ('divorced', 'Divorciado'), ('widowed', 'Viudo')], default='married', max_length=15, null=True, verbose_name='Estado civil'),
        ),
        migrations.AlterField(
            model_name='father',
            name='proffession',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Profesi\xf3n u oficio'),
        ),
        migrations.AlterField(
            model_name='father',
            name='work_address',
            field=models.TextField(blank=True, null=True, verbose_name='Direcci\xf3n de trabajo'),
        ),
        migrations.AlterField(
            model_name='father',
            name='work_charge',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Cargo que desempe\xf1a'),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Direcci\xf3n'),
        ),
        migrations.AlterField(
            model_name='student',
            name='alergies_illnesses',
            field=models.TextField(blank=True, null=True, verbose_name='Alergias o enfermedades'),
        ),
        migrations.AlterField(
            model_name='student',
            name='blood_type',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Tipo de sangre'),
        ),
        migrations.AlterField(
            model_name='student',
            name='born_city',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Ciudad de nacimiento'),
        ),
        migrations.AlterField(
            model_name='student',
            name='born_country',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Pa\xeds de nacimiento'),
        ),
        migrations.AlterField(
            model_name='student',
            name='food_alergies',
            field=models.TextField(blank=True, null=True, verbose_name='Al\xe9rgico a alimentos'),
        ),
        migrations.AlterField(
            model_name='student',
            name='identity',
            field=models.CharField(blank=True, db_index=True, max_length=60, null=True, verbose_name='Identidad'),
        ),
        migrations.AlterField(
            model_name='student',
            name='medicine_alergies',
            field=models.TextField(blank=True, null=True, verbose_name='Al\xe9rgico a medicinas'),
        ),
        migrations.AlterField(
            model_name='student',
            name='medicines',
            field=models.TextField(blank=True, null=True, verbose_name='Medicinas que toma'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Matr\xedcula'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='academic_grade',
            field=models.CharField(blank=True, choices=[('profesionalizandose', 'Profesionaliz\xe1ndose'), ('licenciatura', 'Licenciatura'), ('maestria', 'Maestr\xeda')], max_length=60, null=True, verbose_name='Formaci\xf3n acad\xe9mica'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='college',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Colegiaci\xf3n'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='escalafon',
            field=models.CharField(blank=True, db_index=True, max_length=60, null=True, verbose_name='ESCALAFON'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='grade',
            field=models.CharField(blank=True, db_index=True, max_length=60, null=True, verbose_name='Grado'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='identity',
            field=models.CharField(blank=True, db_index=True, max_length=60, null=True, verbose_name='Identidad'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='inprema',
            field=models.CharField(blank=True, db_index=True, max_length=60, null=True, verbose_name='INPREMA'),
        ),
    ]
