# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-13 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='father',
            name='born_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='father',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electr\xf3nico'),
        ),
        migrations.AddField(
            model_name='father',
            name='employee_type',
            field=models.CharField(choices=[('permanent', 'Empleado permanente'), ('contractor', 'Por contrato'), ('both', 'Ambas')], default='permanent', max_length=60),
        ),
        migrations.AddField(
            model_name='father',
            name='have_job',
            field=models.BooleanField(default=True, verbose_name='Labora actualmente'),
        ),
        migrations.AddField(
            model_name='father',
            name='marital_status',
            field=models.CharField(choices=[('single', 'Soltero'), ('married', 'Casado'), ('divorced', 'Divorciado'), ('widowed', 'Viudo')], default='married', max_length=15, verbose_name='Estado civil'),
        ),
        migrations.AddField(
            model_name='father',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='N\xfamero telef\xf3nico'),
        ),
        migrations.AddField(
            model_name='father',
            name='proffession',
            field=models.CharField(default='', max_length=60, verbose_name='Profesi\xf3n u oficio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='father',
            name='responsible_for_payment',
            field=models.BooleanField(default=False, verbose_name='Est\xe1 encargado del pago de colegiatura'),
        ),
        migrations.AddField(
            model_name='father',
            name='responsible_for_student',
            field=models.BooleanField(default=False, verbose_name='Est\xe1 encargado de sus hijos'),
        ),
        migrations.AddField(
            model_name='father',
            name='work_address',
            field=models.TextField(default='', verbose_name='Direcci\xf3n de trabajo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='father',
            name='work_charge',
            field=models.CharField(default='', max_length=60, verbose_name='Cargo que desempe\xf1a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(default='', verbose_name='Direcci\xf3n'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='alergies_illnesses',
            field=models.TextField(default='', verbose_name='Alergias o enfermedades'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='blood_type',
            field=models.CharField(default='', max_length=4, verbose_name='Tipo de sangre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='born_city',
            field=models.CharField(default='', max_length=60, verbose_name='Ciudad de nacimiento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='born_country',
            field=models.CharField(default='Honduras', max_length=60, verbose_name='Pa\xeds de nacimiento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='born_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='student',
            name='food_alergies',
            field=models.TextField(default='', verbose_name='Al\xe9rgico a alimentos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='identity',
            field=models.CharField(db_index=True, default='', max_length=60, verbose_name='Identidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='medicine_alergies',
            field=models.TextField(default='', verbose_name='Al\xe9rgico a medicinas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='medicines',
            field=models.TextField(default='', verbose_name='Medicinas que toma'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='N\xfamero telef\xf3nico'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='academic_grade',
            field=models.CharField(choices=[('profesionalizandose', 'Profesionaliz\xe1ndose'), ('licenciatura', 'Licenciatura'), ('maestria', 'Maestr\xeda')], default='', max_length=60, verbose_name='Formaci\xf3n acad\xe9mica'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='college',
            field=models.CharField(default='', max_length=60, verbose_name='Colegiaci\xf3n'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electr\xf3nico'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='escalafon',
            field=models.CharField(db_index=True, default='', max_length=60, verbose_name='ESCALAFON'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='grade',
            field=models.CharField(db_index=True, default='', max_length=60, verbose_name='Grado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='identity',
            field=models.CharField(db_index=True, default='', max_length=60, verbose_name='Identidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='inprema',
            field=models.CharField(db_index=True, default='', max_length=60, verbose_name='INPREMA'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='N\xfamero telef\xf3nico'),
        ),
    ]
