# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-17 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='grade',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administration.Grade'),
        ),
    ]
