# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-19 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified at')),
                ('name', models.CharField(max_length=60, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=60, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Descipci\xf3n')),
                ('due_date', models.DateField(verbose_name='Fecha de entrega')),
                ('value', models.FloatField(verbose_name='Valor en calificaci\xf3n final')),
                ('need_response', models.BooleanField(default=False, verbose_name='El alumno debe enviar respuesta')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Course', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
            },
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together=set([('course', 'slug')]),
        ),
    ]
