# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-03 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified at')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='Calificaci\xf3n')),
                ('response', models.TextField(verbose_name='Respuesta')),
                ('file', models.FileField(upload_to=b'', verbose_name='Archivo adjunto')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Student', verbose_name='Estudiante')),
            ],
            options={
                'ordering': ['task', 'student', 'score'],
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified at')),
                ('name', models.CharField(max_length=60, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=60, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Descipci\xf3n')),
                ('due_date', models.DateField(db_index=True, verbose_name='Fecha de entrega')),
                ('value', models.FloatField(verbose_name='Valor en calificaci\xf3n final')),
                ('need_response', models.BooleanField(default=False, verbose_name='El alumno debe enviar respuesta')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Course', verbose_name='Curso')),
            ],
            options={
                'ordering': ['course', 'due_date', 'slug'],
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
            },
        ),
        migrations.AddField(
            model_name='response',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Task', verbose_name='Tarea'),
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together=set([('course', 'slug')]),
        ),
        migrations.AlterUniqueTogether(
            name='response',
            unique_together=set([('task', 'student')]),
        ),
    ]
