# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-19 18:44
from __future__ import unicode_literals

import TCA.tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-due_date', 'course', 'slug'], 'verbose_name': 'Tarea', 'verbose_name_plural': 'Tareas'},
        ),
        migrations.AddField(
            model_name='task',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=TCA.tasks.models.get_file_path, verbose_name='Archivo adjunto'),
        ),
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=TCA.tasks.models.get_file_path, verbose_name='Im\xe1gen'),
        ),
        migrations.AddField(
            model_name='task',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=TCA.tasks.models.get_file_path, verbose_name='Archivo PDF'),
        ),
        migrations.AddField(
            model_name='task',
            name='youtube',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='YouTube'),
        ),
    ]
