# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-19 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20160819_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(db_index=True, verbose_name='Fecha de entrega'),
        ),
    ]
