# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-22 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
        ('tasks', '0003_auto_20160819_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified at')),
                ('score', models.FloatField(verbose_name='Calificaci\xf3n')),
                ('response', models.TextField(verbose_name='Respuesta')),
                ('file', models.FileField(upload_to=b'', verbose_name='Archivo adjunto')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Student', verbose_name='Estudiante')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Task', verbose_name='Tarea')),
            ],
            options={
                'ordering': ['task', 'student', 'score'],
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
            },
        ),
        migrations.AlterUniqueTogether(
            name='response',
            unique_together=set([('task', 'student')]),
        ),
    ]
