# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-19 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Fecha'),
        ),
    ]
