# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-09 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filepost',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='posts.Post', verbose_name='Post'),
        ),
        migrations.AlterField(
            model_name='imagepost',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='posts.Post', verbose_name='Post'),
        ),
        migrations.AlterField(
            model_name='pdfpost',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='posts.Post', verbose_name='Post'),
        ),
        migrations.AlterField(
            model_name='simplepost',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='posts.Post', verbose_name='Post'),
        ),
    ]
